name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Setup gcloud
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: GAR Docker Build & Push
        run:  gcloud builds submit --tag ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_APPNAME }}/${{ vars.GCP_GARREPO }}/${{ vars.GCP_GAR_IMAGE_NAME }}:latest .
